export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";

export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const GET_CHANNEL_BY_ID = "GET_CHANNEL_BY_ID";
export const POST_CHANNEL = "POST_CHANNEL";
export const FILTER_CHANNELS = "FILTER_CHANNELS";
export const SET_CHANNEL_LOADING = "SET_CHANNEL_LOADING";

export const FILTER_MESSAGES = "FILTER_MESSAGES";
export const FETCH_MESSAGE_LIST = "FETCH_MESSAGE_LIST";
export const FETCH_MESSAGE_LIST_WITH_TIMESTAMP =
  "FETCH_MESSAGE_LIST_WITH_TIMESTAMP";
export const POST_MESSAGE = "POST_MESSAGE";
export const SET_MESSAGES_LOADING = "SET_MESSAGES_LOADING";
