export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const GET_CHANNEL_BY_ID = "GET_CHANNEL_BY_ID";
export const POST_CHANNEL = "POST_CHANNEL";
export const FETCH_MESSAGE_LIST = "FETCH_MESSAGE_LIST";
export const FETCH_MESSAGE_LIST_WITH_TIMESTAMP =
  "FETCH_MESSAGE_LIST_WITH_TIMESTAMP";
export const POST_MESSAGE = "POST_MESSAGE";
